apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: g4b7tk203-nodejs-gitops
  description: This is GitOps manifest for g4b7tk203-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=g4b7tk203-nodejs
    backstage.io/kubernetes-id: g4b7tk203-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: g4b7tk203-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:g4b7tk203-nodejs
